<?php

namespace AppBundle\Repository;

/**
 * PartierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartierRepository extends \Doctrine\ORM\EntityRepository
{
}
